import { all, takeLatest, takeLeading, takeEvery } from 'redux-saga/effects'
import {
  HANDLE_MENU_ITEM,
  GET_STARTUPS,
  GET_RETAILERS,
  APPROVE_USER,
  HANDLE_STARTUP_ACTIVATION,
  HANDLE_RETAILER_ACTIVATION,
  GET_PROFILE_STARTUP,
  HANDLE_STARTUP_PROFILE_ACTIVATION,
  APPROVE_USER_PROFILE,
  UPDATE_COMPANY_DETAILS_PROFILE,
  UPDATE_SECTOR_OF_COMPETENCE_PROFILE,
  UPDATE_AREAS_OF_INTEREST_PROFILE,
  UPDATE_TAGS_PROFILE,
  UPDATE_ACCOUNT_INFORMATION,
  HANDLE_UPLOAD_DOCUMENTS_PROFILE,
  HANDLE_REMOVE_DOCUMENTS_PROFILE,
  HANDLE_MAILING,
  UPLOAD_PROFILE_LOGO,
  UPLOAD_USER_AVATAR,
  HANDLE_STARTUP_FILTERS,
  RESET_STARTUP_FILTERS,
  HANDLE_SEARCH_REQUEST,
  GET_FEEDBACKS,
  HANDLE_UPDATE_FEEDBACK,
  HANDLE_REMOVE_FEEDBACK,
  UPDATE_ADMIN_NOTE,
  SEND_ADMIN_NOTIFICATION,
  GET_CATEGORIES,
  HANDLE_CREATE_CATEGORY,
  HANDLE_UPDATE_CATEGORY,
  HANDLE_DELETE_CATEGORY,
  HANDLE_RETAILER_FILTERS,
  RESET_RETAILER_FILTERS,
  HANDLE_VERIFY_USER,
  GET_PROFILE_RETAILER,
  HANDLE_VERIFY_PROFILE,
  GET_REPORTS,
  UPDATE_REPORT_STATUS,
  UPDATE_BILLING_ADDRESS,
  GET_CATEGORIES_ACTIVITY,
  GET_PROFILES_ACTIVITY,
  GET_BOOKMARKS_STARTUPS,
  CHANGE_FILTER_OF_BOOKMARKS,
  GET_RATED_STARTUPS,
  CHANGE_FILTER_OF_RATED_STARTUPS,
  GET_COMPANY_MEMBERS,
  GET_SUBSCRIPTION_PLANS,
  GET_ALL_PAYMENT_PLANS_NAMES,
  GET_PRICES,
  SAVE_NEW_SUBSCRIPTION_PLAN,
  GET_MEMBER_GROUPS,
  EDIT_SUBSCRIPTION_PLAN,
  DELETE__SUBSCRIPTION_PLAN,
  GET_FEATURES,
  CREATE_NEW_FEATURE,
  EDIT_FEATURE,
  DELETE_FEATURE,
  CREATE_NEW_MEMBER_GROUP,
  EDIT_MEMBER_GROUP,
  DELETE_MEMBER_GROUP,
  GET_ENTERPRISE_CODES,
  EDIT_ENTERPRISE_CODE,
  CHANGE_USER_TWO_FA,
  CHANGE_PAYMENT_PLAN_STATUS,
  GET_PAYMENT_RECEIPTS
} from './index'

import {
  handleMenuItemWorker,
  getStartupsWorker,
  getRetailersWorker,
  approveUserWorker,
  handleStartupActivationWorker,
  handleRetailerActivationWorker,
  getStartupProfileWorker,
  handleProfileStartupActivationWorker,
  approveUserProfileWorker,
  updateCompanyDetailsProfileWorker,
  updateSectorOfCompetenceStartupWorker,
  updateAreasOfInterestStartupWorker,
  updateTagsStartupWorker,
  updateAccountInformationWorker,
  handleUploadDocumentsWorker,
  handleRemoveDocumentWorker,
  mailingProfileWorker,
  uploadLogoProfileWorker,
  uploadUserAvatarProfileWorker,
  setSelectedStartupFiltersWorker,
  resetStartupFiltersWorker,
  setSearchRequestFiltersWorker,
  getFeedbacksInfoWorker,
  handleUpdateFeedbacksWorker,
  handleRemoveFeedbacksWorker,
  updateAdminNoteWorker,
  sendAdminNotificationWorker,
  getCategoriesWorker,
  createCategoryWorker,
  updateCategoryWorker,
  deleteCategoryWorker,
  setSelectedRetailerFiltersWorker,
  resetRetailersFiltersWorker,
  verifyUserWorker,
  getRetailerProfileWorker,
  verifyProfileWorker,
  getReportsWorker,
  updateReportStatusWorker,
  updateBillingAddressWorker,
  getCategoriesActivityWorker,
  getProfilesActivityWorker,
  getBookmarksStartupsWorker,
  changeFilterBookmarksStartupsWorker,
  getRatedStartupsWorker,
  changeFilterRatedStartupsWorker,
  getCompanyMembersWorker,
  changeUserTwoFaWorker,
  getSubscriptionPlansWorker,
  getAllPaymentPlansNamesWorker,
  getPricesWorker,
  saveNewSubscriptionPlanWorker,
  getMemberGroupsWorker,
  editSubscriptionPlanWorker,
  deleteSubscriptionPlanWorker,
  getFeaturesWorker,
  createNewFeatureWorker,
  editFeatureWorker,
  deleteFeatureWorker,
  createNewMemberGroupWorker,
  editMemberGroupWorker,
  deleteMemberGroupWorker,
  getEnterpriseCodesWorker,
  editEnterpriseCodeWorker,
  changePaymentPlanStatusWorker,
  getPaymentReceiptsWorker
} from './sagas'

export function* authSaga() {
  all([
    yield takeLatest(HANDLE_MENU_ITEM, handleMenuItemWorker),
    yield takeLeading(GET_STARTUPS, getStartupsWorker),
    yield takeLeading(GET_RETAILERS, getRetailersWorker),
    yield takeLatest(APPROVE_USER, approveUserWorker),
    yield takeLatest(APPROVE_USER_PROFILE, approveUserProfileWorker),
    yield takeLatest(HANDLE_STARTUP_ACTIVATION, handleStartupActivationWorker),
    yield takeLatest(HANDLE_STARTUP_PROFILE_ACTIVATION, handleProfileStartupActivationWorker),
    yield takeLatest(HANDLE_RETAILER_ACTIVATION, handleRetailerActivationWorker),
    yield takeEvery(GET_PROFILE_STARTUP, getStartupProfileWorker),
    yield takeEvery(GET_PROFILE_RETAILER, getRetailerProfileWorker),
    yield takeEvery(UPDATE_COMPANY_DETAILS_PROFILE, updateCompanyDetailsProfileWorker),
    yield takeEvery(UPDATE_SECTOR_OF_COMPETENCE_PROFILE, updateSectorOfCompetenceStartupWorker),
    yield takeEvery(UPDATE_AREAS_OF_INTEREST_PROFILE, updateAreasOfInterestStartupWorker),
    yield takeEvery(UPDATE_TAGS_PROFILE, updateTagsStartupWorker),
    yield takeEvery(UPDATE_ACCOUNT_INFORMATION, updateAccountInformationWorker),
    yield takeEvery(HANDLE_UPLOAD_DOCUMENTS_PROFILE, handleUploadDocumentsWorker),
    yield takeEvery(HANDLE_REMOVE_DOCUMENTS_PROFILE, handleRemoveDocumentWorker),
    yield takeEvery(HANDLE_MAILING, mailingProfileWorker),
    yield takeEvery(UPLOAD_PROFILE_LOGO, uploadLogoProfileWorker),
    yield takeEvery(UPLOAD_USER_AVATAR, uploadUserAvatarProfileWorker),
    yield takeEvery(HANDLE_STARTUP_FILTERS, setSelectedStartupFiltersWorker),
    yield takeEvery(HANDLE_RETAILER_FILTERS, setSelectedRetailerFiltersWorker),
    yield takeEvery(RESET_STARTUP_FILTERS, resetStartupFiltersWorker),
    yield takeEvery(RESET_RETAILER_FILTERS, resetRetailersFiltersWorker),
    yield takeEvery(HANDLE_SEARCH_REQUEST, setSearchRequestFiltersWorker),
    yield takeEvery(GET_FEEDBACKS, getFeedbacksInfoWorker),
    yield takeEvery(HANDLE_UPDATE_FEEDBACK, handleUpdateFeedbacksWorker),
    yield takeEvery(HANDLE_REMOVE_FEEDBACK, handleRemoveFeedbacksWorker),
    yield takeEvery(UPDATE_ADMIN_NOTE, updateAdminNoteWorker),
    yield takeLeading(SEND_ADMIN_NOTIFICATION, sendAdminNotificationWorker),
    yield takeEvery(GET_CATEGORIES, getCategoriesWorker),
    yield takeEvery(HANDLE_CREATE_CATEGORY, createCategoryWorker),
    yield takeEvery(HANDLE_UPDATE_CATEGORY, updateCategoryWorker),
    yield takeEvery(HANDLE_DELETE_CATEGORY, deleteCategoryWorker),
    yield takeEvery(HANDLE_VERIFY_USER, verifyUserWorker),
    yield takeEvery(HANDLE_VERIFY_PROFILE, verifyProfileWorker),
    yield takeEvery(GET_REPORTS, getReportsWorker),
    yield takeEvery(UPDATE_REPORT_STATUS, updateReportStatusWorker),
    yield takeEvery(UPDATE_BILLING_ADDRESS, updateBillingAddressWorker),
    yield takeEvery(GET_CATEGORIES_ACTIVITY, getCategoriesActivityWorker),
    yield takeEvery(GET_PROFILES_ACTIVITY, getProfilesActivityWorker),
    yield takeLatest(GET_BOOKMARKS_STARTUPS, getBookmarksStartupsWorker),
    yield takeLatest(CHANGE_FILTER_OF_BOOKMARKS, changeFilterBookmarksStartupsWorker),
    yield takeLatest(GET_RATED_STARTUPS, getRatedStartupsWorker),
    yield takeLatest(CHANGE_FILTER_OF_RATED_STARTUPS, changeFilterRatedStartupsWorker),
    yield takeLeading(GET_COMPANY_MEMBERS, getCompanyMembersWorker),
    yield takeLeading(CHANGE_USER_TWO_FA, changeUserTwoFaWorker),
    yield takeLeading(GET_FEATURES, getFeaturesWorker),
    yield takeLeading(CREATE_NEW_FEATURE, createNewFeatureWorker),
    yield takeLeading(EDIT_FEATURE, editFeatureWorker),
    yield takeLeading(DELETE_FEATURE, deleteFeatureWorker),
    yield takeLeading(GET_SUBSCRIPTION_PLANS, getSubscriptionPlansWorker),
    yield takeLeading(GET_PAYMENT_RECEIPTS, getPaymentReceiptsWorker),
    yield takeLeading(GET_ALL_PAYMENT_PLANS_NAMES, getAllPaymentPlansNamesWorker),
    yield takeLeading(GET_PRICES, getPricesWorker),
    yield takeLeading(SAVE_NEW_SUBSCRIPTION_PLAN, saveNewSubscriptionPlanWorker),
    yield takeLeading(GET_MEMBER_GROUPS, getMemberGroupsWorker),
    yield takeLeading(CREATE_NEW_MEMBER_GROUP, createNewMemberGroupWorker),
    yield takeLeading(EDIT_MEMBER_GROUP, editMemberGroupWorker),
    yield takeLeading(DELETE_MEMBER_GROUP, deleteMemberGroupWorker),
    yield takeLeading(EDIT_SUBSCRIPTION_PLAN, editSubscriptionPlanWorker),
    yield takeLeading(DELETE__SUBSCRIPTION_PLAN, deleteSubscriptionPlanWorker),
    yield takeLeading(GET_ENTERPRISE_CODES, getEnterpriseCodesWorker),
    yield takeLeading(EDIT_ENTERPRISE_CODE, editEnterpriseCodeWorker),
    yield takeLeading(CHANGE_PAYMENT_PLAN_STATUS, changePaymentPlanStatusWorker)
  ])
}

export default authSaga
